from bs4 import BeautifulSoup
from model.browser import SeleniumDriver
from model.context import Context
from model.nodes import get_node_class

# --- DATA STRUCTURES ---
# We use a simple list of dictionaries to represent the "Workflow Plan"
# Example: [{'type': 'extract', 'selector': 'h1', 'name': 'Title'}, ...]

class ScraperEngine:
    """
    The brain that executes the workflow plan.
    """
    def __init__(self):
        self.current_row = {}
        self.results = []  # Final data list
        self.stop_flag = False
        self.current_url = None

    def run(self, steps, base_url, browser: SeleniumDriver, ctx:Context):
        self.stop_flag = False
        ctx.stop_event.clear()
        self.current_url = base_url
        current_url = base_url
        ctx.push_message("info", f"--- Starting Job on {current_url} ---")

        try:
            browser.visit_page(current_url, ctx)
            # Start the recursive processing
            # We treat the initial page as a single item context
            self.results = self.process_steps(steps, ctx, browser)

        except Exception as e:
            ctx.push_message("error", f"Critical Engine Error: {e}")
        finally:
            ctx.push_message("info", f"--- Job Complete. Extracted {len(self.results)} rows. ---")
        return self.results


    def process_steps(self, steps, context, browser, context_soup=None, inherited_data=None):
        """
        :param context_soup: If None, we are at Root Level (Page Context).
                             If Set, we are inside a Loop (Element Context).
        """
        is_root_context = (context_soup is None)
        # 1. Start with Inherited Data (Fixes Data Amnesia)
        local_data = inherited_data.copy() if inherited_data else {}

        # We will collect all rows generated by child loops here
        child_rows = []
        for step_config in steps:
            if is_root_context:
                # We are looking at the whole page.
                # Always get the latest state from the browser before running a step.
                # This ensures we see the results of previous Clicks immediately.
                html = browser.driver.page_source
                current_soup = BeautifulSoup(html, 'html.parser')
            else:
                # We are locked inside a specific element (Loop).
                # DO NOT refresh, or we lose our place in the list.
                current_soup = context_soup
            action_type = step_config.get('type')
            print(browser.driver.page_source)
            # 1. Get the correct class (e.g., ExtractAction)
            NodeClass = get_node_class(action_type)

            if not NodeClass:
                print(f"Unknown step type: {action_type}")
                continue

            # 2. Instantiate and Execute
            action_instance = NodeClass()

            # Execute logic
            result = action_instance.execute(step_config, context, browser, self, context_soup=current_soup, inherited_data=local_data)

            # --- HANDLE RETURN VALUES ---

            # Case A: Node returned a Data Update (ExtractNode)
            if isinstance(result, dict):
                local_data.update(result)

            # Case B: Node returned a List of Rows (LoopNode / RepeatNode)
            elif isinstance(result, list):
                child_rows.extend(result)

        # --- FINAL DECISION ---

        # If child loops ran, they did the heavy lifting. Return their rows.
        if child_rows:
            return child_rows

        # If no loops ran, WE are the leaf. Return the single row we built.
        # We wrap it in a list to maintain consistency (always return List[dict])
        elif local_data:
            return [local_data]

        return []